name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run a one-line script
        run: |
          cd ~/backend/backend
          git pull origin main
          npm install
          npm run build
