name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run a one-line script
        run: |
          cd ~/backend
          echo "connect!!"
          whoami
          git clone https://github.com/dmin0211/Web-DB-Module
        
