name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: cocoo-server

    steps:
      - name: Run a one-line script
        run: touch test.txt
